// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz1LaxDEmEvVWbXraRFb286P58Tv7wlNc',
    appId: '1:313491771538:web:90d650d5f7150adaf0964b',
    messagingSenderId: '313491771538',
    projectId: 'challengr-database',
    authDomain: 'challengr-database.firebaseapp.com',
    storageBucket: 'challengr-database.appspot.com',
    measurementId: 'G-6R19RL9NHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIDjKG-LY6P6m_xH6AnOtl95DTA8YYKlU',
    appId: '1:313491771538:android:117a5ffe9fd72780f0964b',
    messagingSenderId: '313491771538',
    projectId: 'challengr-database',
    storageBucket: 'challengr-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuHFBGKTtYrXNBsVtd6-ka1wqzlyOSSpM',
    appId: '1:313491771538:ios:3a9b8accacbc2c13f0964b',
    messagingSenderId: '313491771538',
    projectId: 'challengr-database',
    storageBucket: 'challengr-database.appspot.com',
    iosBundleId: 'com.example.prog2JowiDaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuHFBGKTtYrXNBsVtd6-ka1wqzlyOSSpM',
    appId: '1:313491771538:ios:3a9b8accacbc2c13f0964b',
    messagingSenderId: '313491771538',
    projectId: 'challengr-database',
    storageBucket: 'challengr-database.appspot.com',
    iosBundleId: 'com.example.prog2JowiDaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz1LaxDEmEvVWbXraRFb286P58Tv7wlNc',
    appId: '1:313491771538:web:d099bb28e766c97ff0964b',
    messagingSenderId: '313491771538',
    projectId: 'challengr-database',
    authDomain: 'challengr-database.firebaseapp.com',
    storageBucket: 'challengr-database.appspot.com',
    measurementId: 'G-5B6ZD0CPSC',
  );
}
